version: '3.8'

services:
  simple-notes:
    build:
      context: ./simple-notes
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./simple-notes/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    networks:
      - webnet

  backend:
    build:
      context: ./SimpleNotes
    command: >
      sh -c "python manage.py migrate &&
             gunicorn SimpleNotes.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./SimpleNotes:/app
    ports:
      - "8000:8000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
