version: "3.9"

services:
  django:
    container_name: django_app
    build:
      context: ./SimpleNotes
    command: >
      sh -c "python manage.py migrate &&
             gunicorn SimpleNotes.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./SimpleNotes:/app
    ports:
      - "8000:8000"

  react:
    container_name: react_app
    build:
      context: ./simple-notes
    volumes:
      - ./simple-notes/src:/app/src
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - django
      - react
