# Generated by Django 5.1 on 2024-08-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Проверка почты',
                'verbose_name_plural': 'Проверки почты',
            },
        ),
    ]
