# Generated by Django 5.1 on 2024-08-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0005_emailverification_attempts_emailverification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
