# Generated by Django 5.1 on 2024-08-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0006_alter_emailverification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
