# Generated by Django 5.1 on 2024-08-20 19:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0007_alter_emailverification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 56, 30, 205958, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('expired_time', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 19, 53, 30, 208958, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.user')),
            ],
        ),
    ]
