# Generated by Django 5.1 on 2024-08-20 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0009_alter_apikey_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API ключ', 'verbose_name_plural': 'API ключи'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 22, 43, 18, 408973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 22, 46, 18, 403972, tzinfo=datetime.timezone.utc)),
        ),
    ]
