# Generated by Django 5.1 on 2024-08-21 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0010_alter_apikey_options_alter_apikey_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 10, 27, 12, 447470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 10, 30, 12, 444471, tzinfo=datetime.timezone.utc)),
        ),
    ]
