# Generated by Django 5.1 on 2024-08-21 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0011_alter_apikey_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 13, 5, 48, 556527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 13, 8, 48, 554527, tzinfo=datetime.timezone.utc)),
        ),
    ]
