# Generated by Django 5.1 on 2024-08-22 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0012_alter_apikey_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 1, 17, 44, 663892, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 0, 22, 44, 661892, tzinfo=datetime.timezone.utc)),
        ),
    ]
