# Generated by Django 5.1 on 2024-08-23 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0013_alter_apikey_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 16, 38, 42, 585999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 15, 43, 42, 583999, tzinfo=datetime.timezone.utc)),
        ),
    ]
