# Generated by Django 5.1 on 2024-08-21 10:25

import Notes.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(default=Notes.utils.get_created_date)),
                ('updated_time', models.DateTimeField(default=Notes.utils.get_created_date)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.group')),
            ],
        ),
    ]
