# Generated by Django 5.1 on 2024-08-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0013_alter_apikey_expired_time_and_more'),
        ('Notes', '0002_note_user_alter_note_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.user'),
            preserve_default=False,
        ),
    ]
